### ISSUE TITLE
Pistons Lag with over 300 users

### ISSUE THREAD

**Issue by fra130701** [Axionize/LightningGrim#67]
### Describe the bug and how to replicate it

![Image](https://github.com/user-attachments/assets/64867459-1fbf-43f3-bdd5-7a49ffea3727)

### Grim version

2.3.71 b62

### Server version

UniverseSpigot 1.21.1

### Plugins

Not Needed for this report

**Comment by andreasdc** [comment]
Is isChunkLoaded worth checking there? Chunk will be loaded on PistonEvent, right?

**Comment by Axionize** [comment]
> Is isChunkLoaded worth checking there? Chunk will be loaded on PistonEvent, right?

No. It is fully possible for a chunk to be loaded server side but not client side after accounting for latency in client side modeling. More importantly, in addition while this event is fired for the entire server. Meaning for some player this will be in unloaded chunks for them.

I've addressed some of this in my work in platform-independence upstream which improves performance by running the isChunkLoaded off a different thread and fixes a rare related race condition which causes an error. I'll be porting this to LightningGrim soon™. If piston behavior is not particularly important to you take a look at the redstone limiter in USpigot for now.

Also please do not tag performance scaling issues as "bugs"

**Comment by andreasdc** [comment]
> > Is isChunkLoaded worth checking there? Chunk will be loaded on PistonEvent, right?
> 
> No. It is fully possible for a chunk to be loaded server side but not after accounting for latency in client side modeling. More importantly, in addition while this event is fired for the entire server. Meaning for some player this will be in unloaded chunks for them.
> 
> I've addressed some of this in my work in platform-independence upstream which improves performance by running the isChunkLoaded off a different thread and fixes a rare related race condition which causes an error. I'll be porting this to LightningGrim soon™. If piston behavior is not particularly important to you take a look at the redstone limiter in USpigot for now.
> 
> Also please do not tag performance scaling issues as "bugs"

I mean if you check for the chunk loaded on piston event, the chunk is already loaded, right?

**Comment by Axionize** [comment]
> I mean if you check for the chunk loaded on piston event, the chunk is already loaded, right?

No, as I have already very clearly explained to you.

**Comment by andreasdc** [comment]
Well you edited in 7 times, yet I still don't understand. What does the client has to do with server side loaded chunk? Piston already moved, the chunk is loaded, right?

**Comment by Axionize** [comment]
Grim maintains **per-player** latency compensated models of the world. This means that chunks can be loaded by the server but be **unloaded for another player** in another area or with much lower render distance. 


This means that the event has no effect (and thus shouldn't be processed for):
1. **Player's in other parts of the world or other worlds**: Bukkit Events like Piston Retraction and Push are fired on the main server side without any context as to which players it is fired for (which makes sense because a piston can move in a chunk such as spawn chunks even when there are no players nearby). Thus if you are at 0 0 and a piston fires next to you, while that means we have to update your compensated world model for you, this has nothing to do with a player at x: 1000, z: 1000 who's client doesn't even know the piston exists.

2. **Player's who have already moved out of the area**:  Its perfectly possible for a player on say 500 ms ping who client-side has just moved out of the area containing the piston to not need to process the event. This is a classic side effect of multi-threading, where a player's movements can be processed in parallel on another thread. If everything was executed on the main thread this case would not have to be handled since it would be guarantied no state would change as you would be executing the event handling without interference from any other threads or code.

3. **Threading issues**: Since these events are fired on the main server thread (or respective region thread on Folia) and most of our processing happens on the player netty thread (including managing the compensated world) checking for isChunkLoaded() on the main thread is unsafe (which I've fixed upstream but not in LightningGrim yet) and can lead to errors.


Basically, it (and more) boils down to "just because a chunk is loaded server side doesn't mean its loaded client side for every player on the server" and "these events are fired on the main thread whereas almost all of Grim code is executed in player netty threads"

If you still do not understand I encourage you to join our Discord.

GitHub issues are also not place for extending discussions on topics like this unrelated to shedding more light on or fixing the issue for contributors. Questions like these should be asked on the Discord:  https://discord.gg/zAHTjmgGFz and I politely ask that you ask similar questions there in the future.

**Comment by andreasdc** [comment]
Right, I was just saying that you don't exactly need to check if the world chunk is loaded serverside and you could use getChunkIfLoaded (if it exists), but I see that most of the checks are for the compensatedWorld.

**Comment by fra130701** [comment]
`Also please do not tag performance scaling issues as "bugs"`
Sorry for the mistake

`I've addressed some of this in my work in platform-independence upstream which improves performance by running the isChunkLoaded off a different thread and fixes a rare related race condition which causes an error. I'll be porting this to LightningGrim soon™. If piston behavior is not particularly important to you take a look at the redstone limiter in USpigot for now.`
Thanks very much, 
If you need other profiler or something i'm here!

**Comment by Axionize** [comment]
@fra130701 Have my recent optimizations been good enough for your use case? Have you tried the latest LightningGrim?
